### ISSUE TITLE
Infografia Lenguajes de Programacion

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IsraelNicolas61#1]
[LenguajesDeProgramacion_IsraelNicolásPérez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IsraelNicolas61/files/8644468/LenguajesDeProgramacion_IsraelNicolasPerez.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo, calificación obtenida: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
